import React from "react";

export interface DiagramTemplate {
  id: string;
  label: string;
  description: string;
  icon: React.FC;
  content: string;
  defaultName: string;
}

const BlankIcon: React.FC = () =>
  React.createElement(
    "svg",
    {
      width: 28,
      height: 28,
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: 1.5,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    React.createElement("rect", { x: 3, y: 3, width: 18, height: 18, rx: 2 }),
  );

const FlowchartIcon: React.FC = () =>
  React.createElement(
    "svg",
    {
      width: 28,
      height: 28,
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: 1.5,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    React.createElement("rect", { x: 2, y: 3, width: 8, height: 5, rx: 1 }),
    React.createElement("rect", { x: 14, y: 3, width: 8, height: 5, rx: 1 }),
    React.createElement("rect", { x: 8, y: 16, width: 8, height: 5, rx: 1 }),
    React.createElement("line", { x1: 10, y1: 8, x2: 10, y2: 12 }),
    React.createElement("line", { x1: 10, y1: 12, x2: 12, y2: 16 }),
    React.createElement("line", { x1: 18, y1: 8, x2: 18, y2: 12 }),
    React.createElement("line", { x1: 18, y1: 12, x2: 12, y2: 16 }),
  );

const WireframeIcon: React.FC = () =>
  React.createElement(
    "svg",
    {
      width: 28,
      height: 28,
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: 1.5,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    React.createElement("rect", { x: 2, y: 2, width: 20, height: 20, rx: 2 }),
    React.createElement("line", { x1: 2, y1: 7, x2: 22, y2: 7 }),
    React.createElement("line", { x1: 8, y1: 7, x2: 8, y2: 22 }),
  );

const MindMapIcon: React.FC = () =>
  React.createElement(
    "svg",
    {
      width: 28,
      height: 28,
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: 1.5,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    React.createElement("circle", { cx: 12, cy: 12, r: 4 }),
    React.createElement("circle", { cx: 4, cy: 5, r: 2 }),
    React.createElement("circle", { cx: 20, cy: 5, r: 2 }),
    React.createElement("circle", { cx: 4, cy: 19, r: 2 }),
    React.createElement("circle", { cx: 20, cy: 19, r: 2 }),
    React.createElement("line", { x1: 9, y1: 9, x2: 6, y2: 6 }),
    React.createElement("line", { x1: 15, y1: 9, x2: 18, y2: 6 }),
    React.createElement("line", { x1: 9, y1: 15, x2: 6, y2: 18 }),
    React.createElement("line", { x1: 15, y1: 15, x2: 18, y2: 18 }),
  );

function makeExcalidraw(elements: object[]): string {
  return JSON.stringify({
    type: "excalidraw",
    version: 2,
    source: "inspark-draw",
    elements,
    appState: { gridSize: null, viewBackgroundColor: "#ffffff" },
    files: {},
  });
}

export const EMPTY_EXCALIDRAW = makeExcalidraw([]);

export const TEMPLATES: DiagramTemplate[] = [
  {
    id: "blank",
    label: "Blank Canvas",
    description: "Start from scratch",
    icon: BlankIcon,
    content: EMPTY_EXCALIDRAW,
    defaultName: "untitled",
  },
  {
    id: "flowchart",
    label: "Flowchart",
    description: "Start → Process → End",
    icon: FlowchartIcon,
    content: makeExcalidraw([
      {
        id: "tmpl-fc-start",
        type: "rectangle",
        x: 100,
        y: 100,
        width: 160,
        height: 60,
        strokeColor: "#1e1e1e",
        backgroundColor: "#a5d8ff",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 3 },
        boundElements: [{ id: "tmpl-fc-arrow1", type: "arrow" }],
        seed: 1001,
        version: 1,
        versionNonce: 1001,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-start-label",
        type: "text",
        x: 152,
        y: 118,
        width: 56,
        height: 25,
        text: "Start",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "center",
        verticalAlign: "middle",
        containerId: "tmpl-fc-start",
        originalText: "Start",
        lineHeight: 1.25,
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        seed: 1002,
        version: 1,
        versionNonce: 1002,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-process",
        type: "rectangle",
        x: 100,
        y: 240,
        width: 160,
        height: 60,
        strokeColor: "#1e1e1e",
        backgroundColor: "#b2f2bb",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 3 },
        boundElements: [
          { id: "tmpl-fc-arrow1", type: "arrow" },
          { id: "tmpl-fc-arrow2", type: "arrow" },
        ],
        seed: 1003,
        version: 1,
        versionNonce: 1003,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-process-label",
        type: "text",
        x: 135,
        y: 258,
        width: 90,
        height: 25,
        text: "Process",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "center",
        verticalAlign: "middle",
        containerId: "tmpl-fc-process",
        originalText: "Process",
        lineHeight: 1.25,
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        seed: 1004,
        version: 1,
        versionNonce: 1004,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-end",
        type: "rectangle",
        x: 100,
        y: 380,
        width: 160,
        height: 60,
        strokeColor: "#1e1e1e",
        backgroundColor: "#ffc9c9",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 3 },
        boundElements: [{ id: "tmpl-fc-arrow2", type: "arrow" }],
        seed: 1005,
        version: 1,
        versionNonce: 1005,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-end-label",
        type: "text",
        x: 160,
        y: 398,
        width: 40,
        height: 25,
        text: "End",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "center",
        verticalAlign: "middle",
        containerId: "tmpl-fc-end",
        originalText: "End",
        lineHeight: 1.25,
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        seed: 1006,
        version: 1,
        versionNonce: 1006,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-arrow1",
        type: "arrow",
        x: 180,
        y: 160,
        width: 0,
        height: 80,
        points: [
          [0, 0],
          [0, 80],
        ],
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        startBinding: { elementId: "tmpl-fc-start", focus: 0, gap: 1 },
        endBinding: { elementId: "tmpl-fc-process", focus: 0, gap: 1 },
        startArrowhead: null,
        endArrowhead: "arrow",
        seed: 1007,
        version: 1,
        versionNonce: 1007,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-fc-arrow2",
        type: "arrow",
        x: 180,
        y: 300,
        width: 0,
        height: 80,
        points: [
          [0, 0],
          [0, 80],
        ],
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        startBinding: { elementId: "tmpl-fc-process", focus: 0, gap: 1 },
        endBinding: { elementId: "tmpl-fc-end", focus: 0, gap: 1 },
        startArrowhead: null,
        endArrowhead: "arrow",
        seed: 1008,
        version: 1,
        versionNonce: 1008,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
    ]),
    defaultName: "flowchart",
  },
  {
    id: "wireframe",
    label: "Wireframe",
    description: "App layout skeleton",
    icon: WireframeIcon,
    content: makeExcalidraw([
      {
        id: "tmpl-wf-frame",
        type: "rectangle",
        x: 50,
        y: 50,
        width: 500,
        height: 400,
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 3 },
        seed: 2001,
        version: 1,
        versionNonce: 2001,
        isDeleted: false,
        groupIds: [],
        boundElements: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-wf-nav",
        type: "rectangle",
        x: 50,
        y: 50,
        width: 500,
        height: 50,
        strokeColor: "#1e1e1e",
        backgroundColor: "#e9ecef",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: null,
        seed: 2002,
        version: 1,
        versionNonce: 2002,
        isDeleted: false,
        groupIds: [],
        boundElements: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-wf-sidebar",
        type: "rectangle",
        x: 50,
        y: 100,
        width: 120,
        height: 350,
        strokeColor: "#1e1e1e",
        backgroundColor: "#f8f9fa",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: null,
        seed: 2003,
        version: 1,
        versionNonce: 2003,
        isDeleted: false,
        groupIds: [],
        boundElements: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-wf-content",
        type: "rectangle",
        x: 170,
        y: 100,
        width: 380,
        height: 350,
        strokeColor: "#1e1e1e",
        backgroundColor: "#ffffff",
        fillStyle: "solid",
        strokeWidth: 1,
        roundness: null,
        seed: 2004,
        version: 1,
        versionNonce: 2004,
        isDeleted: false,
        groupIds: [],
        boundElements: [],
        updated: 1,
        link: null,
        locked: false,
      },
    ]),
    defaultName: "wireframe",
  },
  {
    id: "mindmap",
    label: "Mind Map",
    description: "Central idea + branches",
    icon: MindMapIcon,
    content: makeExcalidraw([
      {
        id: "tmpl-mm-center",
        type: "ellipse",
        x: 200,
        y: 200,
        width: 160,
        height: 80,
        strokeColor: "#1e1e1e",
        backgroundColor: "#ffec99",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        boundElements: [
          { id: "tmpl-mm-line1", type: "arrow" },
          { id: "tmpl-mm-line2", type: "arrow" },
          { id: "tmpl-mm-line3", type: "arrow" },
          { id: "tmpl-mm-line4", type: "arrow" },
        ],
        seed: 3001,
        version: 1,
        versionNonce: 3001,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-center-label",
        type: "text",
        x: 232,
        y: 225,
        width: 96,
        height: 25,
        text: "Main Idea",
        fontSize: 20,
        fontFamily: 1,
        textAlign: "center",
        verticalAlign: "middle",
        containerId: "tmpl-mm-center",
        originalText: "Main Idea",
        lineHeight: 1.25,
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        seed: 3002,
        version: 1,
        versionNonce: 3002,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-t1",
        type: "ellipse",
        x: 20,
        y: 60,
        width: 120,
        height: 50,
        strokeColor: "#1e1e1e",
        backgroundColor: "#a5d8ff",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        boundElements: [{ id: "tmpl-mm-line1", type: "arrow" }],
        seed: 3003,
        version: 1,
        versionNonce: 3003,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-t2",
        type: "ellipse",
        x: 420,
        y: 60,
        width: 120,
        height: 50,
        strokeColor: "#1e1e1e",
        backgroundColor: "#b2f2bb",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        boundElements: [{ id: "tmpl-mm-line2", type: "arrow" }],
        seed: 3004,
        version: 1,
        versionNonce: 3004,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-t3",
        type: "ellipse",
        x: 20,
        y: 370,
        width: 120,
        height: 50,
        strokeColor: "#1e1e1e",
        backgroundColor: "#ffc9c9",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        boundElements: [{ id: "tmpl-mm-line3", type: "arrow" }],
        seed: 3005,
        version: 1,
        versionNonce: 3005,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-t4",
        type: "ellipse",
        x: 420,
        y: 370,
        width: 120,
        height: 50,
        strokeColor: "#1e1e1e",
        backgroundColor: "#d0bfff",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        boundElements: [{ id: "tmpl-mm-line4", type: "arrow" }],
        seed: 3006,
        version: 1,
        versionNonce: 3006,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-line1",
        type: "arrow",
        x: 200,
        y: 210,
        width: 60,
        height: 120,
        points: [
          [0, 0],
          [-60, -120],
        ],
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        startBinding: { elementId: "tmpl-mm-center", focus: 0, gap: 5 },
        endBinding: { elementId: "tmpl-mm-t1", focus: 0, gap: 5 },
        startArrowhead: null,
        endArrowhead: null,
        seed: 3007,
        version: 1,
        versionNonce: 3007,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-line2",
        type: "arrow",
        x: 360,
        y: 210,
        width: 60,
        height: 120,
        points: [
          [0, 0],
          [60, -120],
        ],
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        startBinding: { elementId: "tmpl-mm-center", focus: 0, gap: 5 },
        endBinding: { elementId: "tmpl-mm-t2", focus: 0, gap: 5 },
        startArrowhead: null,
        endArrowhead: null,
        seed: 3008,
        version: 1,
        versionNonce: 3008,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-line3",
        type: "arrow",
        x: 200,
        y: 270,
        width: 60,
        height: 120,
        points: [
          [0, 0],
          [-60, 120],
        ],
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        startBinding: { elementId: "tmpl-mm-center", focus: 0, gap: 5 },
        endBinding: { elementId: "tmpl-mm-t3", focus: 0, gap: 5 },
        startArrowhead: null,
        endArrowhead: null,
        seed: 3009,
        version: 1,
        versionNonce: 3009,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
      {
        id: "tmpl-mm-line4",
        type: "arrow",
        x: 360,
        y: 270,
        width: 60,
        height: 120,
        points: [
          [0, 0],
          [60, 120],
        ],
        strokeColor: "#1e1e1e",
        backgroundColor: "transparent",
        fillStyle: "solid",
        strokeWidth: 2,
        roundness: { type: 2 },
        startBinding: { elementId: "tmpl-mm-center", focus: 0, gap: 5 },
        endBinding: { elementId: "tmpl-mm-t4", focus: 0, gap: 5 },
        startArrowhead: null,
        endArrowhead: null,
        seed: 3010,
        version: 1,
        versionNonce: 3010,
        isDeleted: false,
        groupIds: [],
        updated: 1,
        link: null,
        locked: false,
      },
    ]),
    defaultName: "mind-map",
  },
];
